import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Inter } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import BlurryBlob from "@/components/animate/background/blurry-blob";
const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body
        className={cn(
          "mb-10 min-h-screen bg-background font-sans antialiased  m-auto",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative">
            <BlurryBlob
              className="absolute z-[-1]"
              firstBlobColor="bg-blue-400"
              secondBlobColor="bg-purple-400"
            />
            <Header />
            <div className="container mx-auto px-5">
              {children}
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
